# Generated by Django 5.1.4 on 2024-12-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_auth", "0002_alter_admin_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
