# Generated by Django 5.1.4 on 2024-12-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("problem_statement", models.TextField()),
                ("solution", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AssociatedLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssociatedFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.framework",
                    ),
                ),
                (
                    "associated_lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.associatedlanguage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssociatedLib",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "associated_lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.associatedlanguage",
                    ),
                ),
                (
                    "lib",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skills.lib"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssociatedOrm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "associated_lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.associatedlanguage",
                    ),
                ),
                (
                    "orm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skills.orm"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deployed_link", models.CharField(max_length=255)),
                ("repo_link", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssociatedTech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.technology",
                    ),
                ),
                (
                    "project_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projectvariant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="associatedlanguage",
            name="project_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.projectvariant",
            ),
        ),
    ]
